version: '3'

services:
  db:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - hipt_nw
    restart: unless-stopped
    volumes:
      - hipt_db:/var/lib/mysql
  cache:
    image: redis:7.0.8-alpine
    ports:
      - "6379:6379"
    networks:
      - hipt_nw
    restart: unless-stopped
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      REDIS_URI: redis://cache:6379/hipt
    depends_on:
      - db
      - cache
    networks:
     - hipt_nw
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    command: ["npm", "run", "start:prod"]

networks:
  hipt_nw:
    driver: bridge

volumes:
  hipt_db: